# Generated by Django 5.2.1 on 2025-05-19 10:28

import datetime
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bic', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='БИК')),
                ('pzn', models.CharField(blank=True, max_length=2, verbose_name='Признак участника')),
                ('rgn', models.CharField(blank=True, max_length=2, verbose_name='Регион')),
                ('ind', models.CharField(blank=True, max_length=6, verbose_name='Индекс')),
                ('tnp', models.CharField(blank=True, max_length=5, verbose_name='Тип населенного пункта')),
                ('nnp', models.CharField(blank=True, max_length=25, verbose_name='Населенный пункт')),
                ('adr', models.TextField(blank=True, verbose_name='Адрес')),
                ('namep', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('newnum', models.CharField(blank=True, max_length=9, verbose_name='Новый номер')),
                ('regn', models.CharField(blank=True, max_length=9, verbose_name='Рег. номер')),
                ('ksnp', models.CharField(blank=True, max_length=20, verbose_name='Корр. счет')),
                ('datein', models.CharField(blank=True, max_length=10, verbose_name='Дата включения')),
                ('cbrfdate', models.CharField(blank=True, max_length=10, verbose_name='Дата файла ЦБ')),
                ('cbrffile', models.CharField(blank=True, max_length=100, verbose_name='Имя файла')),
                ('crc7', models.CharField(blank=True, max_length=20, verbose_name='UID')),
                ('import_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата импорта')),
                ('json_data', models.JSONField(default=dict, verbose_name='Доп. данные')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['namep'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('currency', 'Загрузка курсов валют'), ('banks', 'Загрузка данных банков')], max_length=10, verbose_name='Тип задачи')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Детали выполнения')),
                ('items_processed', models.IntegerField(default=0, verbose_name='Обработано записей')),
            ],
            options={
                'verbose_name': 'Лог задачи',
                'verbose_name_plural': 'Логи задач',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(default='USD', max_length=3, verbose_name='Из валюты')),
                ('to_currency', models.CharField(default='RUB', max_length=3, verbose_name='В валюту')),
                ('conversion_date', models.DateField(default=datetime.date.today, verbose_name='Дата курса')),
                ('conversion_type', models.CharField(choices=[('DAILY', 'Ежедневный курс'), ('WEEKLY', 'Еженедельный курс'), ('MONTHLY', 'Ежемесячный курс')], default='DAILY', max_length=7, verbose_name='Тип курса')),
                ('conversion_rate', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=12, verbose_name='Курс обмена')),
                ('status_code', models.CharField(choices=[('ACTIVE', 'Активный'), ('HISTORICAL', 'Исторический'), ('DELETED', 'Удален')], default='ACTIVE', max_length=10, verbose_name='Статус')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('created_by', models.CharField(default='SYSTEM', max_length=30, verbose_name='Кем создано')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_update_by', models.CharField(default='SYSTEM', max_length=30, verbose_name='Кем обновлено')),
                ('last_update_login', models.CharField(default='AUTO_IMPORT', max_length=30, verbose_name='Логин обновления')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-conversion_date', 'from_currency'],
                'unique_together': {('from_currency', 'to_currency', 'conversion_date')},
            },
        ),
    ]
