# Generated by Django 5.2.1 on 2025-05-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbr_data', '0002_alter_bank_ksnp_alter_bank_regn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='crc7',
            field=models.CharField(blank=True, max_length=25, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ind',
            field=models.CharField(blank=True, max_length=18, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='newnum',
            field=models.CharField(blank=True, max_length=12, verbose_name='Новый номер'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='nnp',
            field=models.CharField(blank=True, max_length=50, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='pzn',
            field=models.CharField(blank=True, max_length=4, verbose_name='Признак участника'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='rgn',
            field=models.CharField(blank=True, max_length=4, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='tnp',
            field=models.CharField(blank=True, max_length=15, verbose_name='Тип населенного пункта'),
        ),
    ]
